using Microsoft.Identity.Client;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TechListApp.ViewModels
{
    public class TechViewModel
    {
        [Key]
        public int Id { get; set; }
        public int QueueId { get; set; } //represents UI order of btns generated by razor pg
        public string Name { get; set; }
        public bool IsHereToday { get; set; } = true;
        public bool IsAvailable { get; set; } = true;
        public bool IsActive => IsHereToday && IsAvailable;
        public bool IsOnlyOneAvailable { get; set; } = false;
    }

}
